# Generated by Django 4.1.3 on 2022-12-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="synopsisPetSex",
            new_name="synopsis",
        ),
    ]
