# Generated by Django 4.1.3 on 2022-12-13 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieorder",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_sold",
                to="movies.movie",
            ),
        ),
        migrations.AlterField(
            model_name="movieorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buys",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
